### ISSUE TITLE
block step does not block things after it

### ISSUE THREAD

**Issue by LennartSpitzner** [buildkite/docs#1467] opened 2022-04-26 17:02 UTC
We have a pipeline that looks like this, and I am simplifying, but hopefully I include the relevant bits:

~~~~
steps:
  - id: "block-foo"
    block: "blocking because on foo-branch"
    branches: foo/*
  - id: "my-step-one"
    if: $somecondition
  - id: "my-step-two"
    depends_on:
      - "my-step-one"
~~~~

What I am observing is that if `somecondition` ends up being false, then `my-step-two` gets executed despite the build being blocked. I _presume_ this is due to it depending on `my-step-one` which implicitly gets unblocked by the false condition (?). We have an additional `wait` (and more steps) between `block-foo` and `my-step-one`, but afaict that does not change the behaviour.

One solution might be to introduce an explicit dependency from `my-step-one` to `block-foo`. The problem is that when not on a `foo/*` branch this implicitly enables the block step.

What _does_ work is to change the block-step to not use `branches: foo/*` but `if: build.branch =~ /^foo\//`, and add an explicitly dependency from `my-step-two` on `block-foo`.

Imo, this leaves some room for improvement:

1) The block step should block all remaining steps, regardless of the dependencies between and the conditionals of those remaining steps. As blocking might be important (getting access to secrets of the CI pipeline etc.) this seems to be a somewhat serious bug. Alternatively, the documentation needs to be updated to point out the issues even when there are no explicitly dependencies from before the block step and after the block step involved.

2) The interaction of conditional steps (`branches` or `if`) and dependencies should be addressed in the documentation.

3) And further, the fact that there is a difference between `branches: foo/*` and `if: build.branch =~ /^foo\//` should be mentioned and discussed in the documentation. I assume that difference is intentional, it kind-of makes sense. Although maybe depending on a build-step that is disabled via `branches` should lead to an error? Dunno.

**Comment by pzeballos** [comment] 2022-04-29 23:34
Hey @LennartSpitzner! 👋🏻

Yes, it's correct, and this is an expected behavior. As is mentioned in the [docs](https://buildkite.com/docs/pipelines/block-step): 

> Block step creates [implicit dependencies](https://buildkite.com/docs/pipelines/dependencies) to the steps before and after it. Note that explicit dependencies specified by depends_on take precedence over implicit dependencies; subsequent steps will run when the step they depend on passes, without waiting for block or wait steps, unless those are also explicit dependencies.

So in this case, the `my-step-two` step "loses" the implicit dependency of the block step, and will have an explicit dependency on the `my-step-one` step.

However, in your situation, `my-step-one` is excluded due to the if condition, thus the dependency will be ignored and the step that depends on it will run once any other dependencies are satisfied.
The order of operations is:

- if/branches
- depends_on
- concurrency_group

You can find more details at https://buildkite.com/docs/pipelines/dependencies#order-of-operations and also you can find examples and more information on the [defining explicit dependencies](https://buildkite.com/docs/pipelines/dependencies#defining-explicit-dependencies) section

> there is a difference between branches: foo/* and if: build.branch =~ /^foo\//

Can you be more specific about the difference you are referring to?  


If you want to share an explicit example from one of your builds, you can send us the link to support@buildkite.com

Thanks!

**Comment by LennartSpitzner** [comment] 2022-05-03 14:02
> So in this case, the `my-step-two` step "loses" the implicit dependency of the block step, and will have an explicit dependency on the `my-step-one` step.

Ok, that explain it, thanks for confirming this understanding. And you are right, the documentation _does_ mention how explicit dependencies override implicit ones.

From the docs:

> However, if the step you're dependent on is excluded from the build due to an if condition, the dependency will be ignored and the step that depends on it will run once any other dependencies are satisfied.

I have to ask: Why are they ignored completely? Imo, when depending on a step that is disabled, the "correct" thing to do is to replace that dependency with the dependencies _of the disabled step_. For in the very simple scenario `b depends-on a` + `c  depends-on b`, there is a transitive dependency `c -> a` (i.e. "c should run after a"). This gets broken by the current behaviour if `b` is disabled (via `if`). With my proposed behaviour, if `b` is disabled, `c` would lose the dependency on `b` but *gain* the dependency on `a` which fixes this.

It seems to me that the semantics here are driven by the implementation, which prunes steps and then proceeds. https://buildkite.com/docs/pipelines/dependencies#order-of-operations hints at this. That is fine, and I understand that rewriting this is too much work. And there _are_ workarounds. Still, its a bit sad that this means that transitive dependencies can be broken so easily and that there is no simple one-liner to block an arbitrary pipeline.

> Can you be more specific about the difference you are referring to?

Ah, I tried reproducing it, but now I noticed I got confused. So actually, `if` and `branches` seem to behave the same, but there still is behaviour that I don't understand and that I don't think is explained by the docs either. Take the pipeline below. Notice that `blocked-branches` runs immediately but `blocked-if` runs later. This is misleading, because it has nothing to do with `if` versus `branches` - if you swap the two `block`s the behaviour swaps as well. So the confusing part here is that the two blocks have an influence even though they are both disabled.

~~~~
steps:
  - label: "Step A"
    command: "sleep 10 && echo a"

  - label: "block branches"
    id: "block-branches"
    branches: never
    block: "foo"
  - label: "block if"
    id: "block-if"
    if: build.branch =~ /^never\//
    block: "foo"

  - label: "blocked-branches"
    depends_on:
      - "block-branches"
    command: "sleep 10 && echo unblocked"
  - label: "blocked-if"
    depends_on:
      - "block-if"
    command: "sleep 10 && echo unblocked"
  ~~~~

**Comment by LennartSpitzner** [comment] 2022-05-03 14:03
And thanks for the quick reply!

**Comment by pzeballos** [comment] 2022-05-20 21:33
Hey @LennartSpitzner! 
Sorry for the delay on this one! 😅

> I have to ask: Why are they ignored completely? 

It was a design decision, but it's very interesting what you mention, and as you said, rewriting it would probably be a significant change, but I'll share your feedback with the team :) 


From your example, it is confusing that you use `id` and `label` with the same name, so I'm not sure which one you are referring to. 

Here you are saying practically the same:
```
  - label: "block branches"
    id: "block-branches"
    branches: never
    block: "foo"
  
  - label: "block if"
    id: "block-if"
    if: build.branch =~ /^never\//
    block: "foo"
```

I'm not sure I understand your situation correctly. But, still, if a step is ready to run, it will be assigned to an agent in priority order (they are executed in the order they were added by the pipeline upload) and to the available agents. So if you have only one agent available, it's going to go run one step first and then the other one. But if you have two available, they are going to run simultaneously.

If you need them to run in a sequence, you can do what the [documentation](https://buildkite.com/docs/pipelines/defining-steps#step-defaults-pipeline-dot-yml-file) suggests:

> If your pipeline has more than one step and you have multiple agents available to run them, they will automatically run simultaneously. If your steps rely on running in sequence, you can separate them with [wait steps](https://buildkite.com/docs/pipelines/wait-step).

**Closed** 2022-05-30 15:34 UTC
