### ISSUE TITLE
Docs don't make it clear that we support Github

### ISSUE THREAD

**Issue by lox** [buildkite/docs#493] opened 2019-06-23 22:35 UTC
Looking at https://buildkite.com/docs/integrations it's not immediately clear that we support GitHub (cloud?) as well as GitHub Enterprise. Let's clearly list it so that folks can be certain we support it.

**Comment by sj26** [comment] 2019-07-01 23:06
Related — https://github.com/buildkite/docs/issues/472

**Comment by sj26** [comment] 2019-07-01 23:07
Maybe a duplicate of https://github.com/buildkite/docs/issues/409

**Comment by harrietgrace** [comment] 2019-10-29 16:15
Closing as a duplicate of #409 🙏🏻

**Closed by harrietgrace** 2019-10-29 16:15 UTC
